/*
 * File: Sencha/FakturyHome/app/view/LineChart.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LineChart', {
    extend: 'Ext.window.Window',

    requires: [
        'MyApp.view.LineChart1'
    ],

    height: 624,
    hidden: false,
    id: 'LineChart',
    width: 966,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    title: 'Okno',
    maximizable: true,
    maximized: false,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'linechart1',
                    flex: 1
                },
                {
                    xtype: 'fieldset',
                    flex: 1,
                    title: 'Faktury Opłacone / Nieopłacone',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Label'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});