/*
 * File: Sencha/FakturyHome/app/view/LineChart1.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LineChart1', {
    extend: 'Ext.chart.Chart',
    alias: 'widget.linechart1',

    height: 250,
    width: 400,
    animate: true,
    insetPadding: 20,
    store: 'WykresGrupyStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            axes: [
                {
                    type: 'Category',
                    position: 'bottom',
                    title: 'Kategoria'
                },
                {
                    type: 'Numeric',
                    fields: [
                        'ilosc'
                    ],
                    position: 'left',
                    title: 'Ilość',
                    adjustMaximumByMajorUnit: true
                }
            ],
            series: [
                {
                    type: 'line',
                    xField: 'ilosc',
                    yField: [
                        'datawystawienia'
                    ],
                    smooth: 3
                },
                {
                    type: 'column',
                    yField: [
                        'ilosc'
                    ],
                    groupGutter: 28
                }
            ]
        });

        me.callParent(arguments);
    }

});