/*
 * File: Sencha/FakturyHome/app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.PieChart1',
        'MyApp.view.LineChart1'
    ],

    layout: {
        align: 'stretch',
        type: 'hbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 2,
                    id: 'mainLeft',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            title: 'Dłużnicy',
                            store: 'DluznicyStore',
                            viewConfig: {

                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'kwota',
                                    text: 'Kwota'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'nazwa',
                                    flex: 1,
                                    text: 'Nazwa'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'objid',
                                    text: 'Objid'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            layout: {
                                type: 'fit'
                            },
                            title: 'Podsumowanie',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    width: 100,
                                    title: '',
                                    store: 'PodsumowanieStore',
                                    viewConfig: {

                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'id',
                                            text: 'Id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            flex: 1,
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ilosc',
                                            text: 'Ilosc'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 2,
                            layout: {
                                type: 'fit'
                            },
                            title: 'Dynamika Przychodu',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    title: '',
                                    store: 'DynamikaPrzychoduStore',
                                    viewConfig: {

                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'okres',
                                            flex: 1,
                                            text: 'Okres'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'wartosc',
                                            text: 'Wartosc'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 5,
                    id: 'mainMiddle',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            autoRender: false,
                            itemId: 'FakturyGrid',
                            styleHtmlContent: false,
                            suspendLayout: true,
                            bodyCls: 'FakturyBody',
                            bodyStyle: 'color: red',
                            title: 'Faktury Nieopłacone',
                            store: 'FakturyStore',
                            viewConfig: {

                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Szukaj:',
                                            listeners: {
                                                change: {
                                                    fn: me.onTextfieldChange,
                                                    scope: me
                                                },
                                                specialkey: {
                                                    fn: me.onTextfieldSpecialkey,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Wyczyść',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                itemcontextmenu: {
                                    fn: me.onGridpanelItemContextMenu,
                                    scope: me
                                }
                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id',
                                    text: 'Id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'name',
                                    text: 'Numer'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'podmiot',
                                    flex: 1,
                                    text: 'Podmiot'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ilosc',
                                    text: 'Kwota'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'datawystawienia',
                                    text: 'Data Wystawienia'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'datazaplaty',
                                    flex: 0.3,
                                    text: 'Ustalona data zapłaty'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            title: 'Zadania Zaplanowane',
                            store: 'ZadaniaStore',
                            viewConfig: {

                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'id',
                                    text: 'Id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'opis',
                                    flex: 1,
                                    text: 'Opis'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'dzienmsc',
                                    text: 'Dzienmsc'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'powtarzaj',
                                    text: 'Powtarzaj'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 3,
                    id: 'mainRight',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    title: 'Faktury opłacone / nieopłacone',
                    items: [
                        {
                            xtype: 'piechart1',
                            theme: 'Purple',
                            flex: 1
                        },
                        {
                            xtype: 'tabpanel',
                            flex: 2,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'Sprzedaż w roku',
                                    dockedItems: [
                                        {
                                            xtype: 'linechart1',
                                            border: 0,
                                            flex: 1,
                                            dock: 'bottom'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ],
                            tools: [
                                {
                                    xtype: 'tool',
                                    listeners: {
                                        click: {
                                            fn: me.onToolClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    tools: [
                        {
                            xtype: 'tool',
                            listeners: {
                                click: {
                                    fn: me.onToolClick1,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    hidden: true,
                    id: 'FakturyChartLabel',
                    layout: {
                        type: 'absolute'
                    }
                },
                {
                    xtype: 'menu',
                    floating: false,
                    hidden: true,
                    id: 'FakturyContext',
                    width: 120,
                    items: [
                        {
                            xtype: 'menuitem',
                            hidden: true,
                            text: 'Oznacz: Opłacona.'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onTextfieldChange: function(field, newValue, oldValue, options) {
        var StoreBuf = Ext.StoreMgr.get("FakturyStore");
        /*var filterBracket = "*"; 
        var filter = filterBracket.concat(newValue);
        filter = filter.concat(filterBracket);
        */
        StoreBuf.clearFilter();
        StoreBuf.filter([
        {
            property:["number","made_for","content"],
            value: newValue,
            anyMatch: true
        }
        ]);

    },

    onTextfieldSpecialkey: function(field, e, options) {
        var StoreBuf = Ext.StoreMgr.get("FakturyStore");
        if (e.button == 7){
            StoreBuf.clearFilter();
            field.fireEvent("change");
        }
    },

    onButtonClick: function(button, e, options) {
        var StoreBuf = Ext.StoreMgr.get("FakturyStore");
        StoreBuf.clearFilter();
        console.log(button.up().down("field").setValue(""));
    },

    onGridpanelItemContextMenu: function(tablepanel, record, item, index, e, options) {
        e.stopEvent();
        var Sklep = tablepanel.getStore();

        var menu = new Ext.menu.Menu({
            items: [{
                text: 'Oznacz jako: Opłacona.',
                handler: function() {
                    console.log(Sklep.data.number);
                    Faktury.isPaid({
                        data: {number: Sklep.getAt(index).data.number},
                        success: Sklep.remove(record),
                        //failure: alert("Napotkano błąd!")
                    });
                }
            }]
        }).showAt(e.xy);
    },

    onToolClick: function(tool, e, options) {
        MyApp.view.LineChart.create()
        Ext.getCmp("LineChart").show()
    },

    onToolClick1: function(tool, e, options) {
        MyApp.view.PieChart.create()
        Ext.getCmp("OknoPieChart").show()
    }

});