/*
 * File: Sencha/FakturyHome/app/view/PieChart.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PieChart', {
    extend: 'Ext.window.Window',

    requires: [
        'MyApp.view.PieChart1'
    ],

    height: 624,
    hidden: false,
    id: 'OknoPieChart',
    width: 966,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    title: 'Okno',
    maximizable: true,
    maximized: false,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'piechart1',
                    id: 'PieChartOkno',
                    stateId: 'PieChartOkno',
                    theme: 'Purple',
                    flex: 1
                },
                {
                    xtype: 'gridpanel',
                    width: 400,
                    title: 'My Grid Panel',
                    store: 'ObrotStore',
                    viewConfig: {
                        listeners: {
                            itemmouseenter: {
                                fn: me.onGridviewItemMouseEnter,
                                scope: me
                            }
                        }
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ilosc',
                            text: 'Ilosc'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'value',
                            text: 'Value'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            flex: 1,
                            text: 'Name'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridviewItemMouseEnter: function(dataview, record, item, index, e, options) {
        var lol = Ext.getCmp("PieChartOkno").series.first()
        lol.highlightItem(lol.items[index])
    }

});