/*
 * File: Sencha/FakturyHome/app/view/PieChart1.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PieChart1', {
    extend: 'Ext.chart.Chart',
    alias: 'widget.piechart1',

    height: 294,
    width: 282,
    animate: true,
    insetPadding: 20,
    store: 'FakturyStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            series: [
                {
                    type: 'pie',
                    highlight: true,
                    tips: {
                        trackMouse: false,
                        width: 140,
                        height: 28,
                        renderer: function(storeItem, item) {
                        this.setTitle(storeItem.get('date') + ': ' + storeItem.get('value'));
                      }
                    },
                    title: 'date',
                    angleField: 'date'
                }
            ]
        });

        me.callParent(arguments);
    }

});